eureka:
  client:
    service-url:
      defaultZone: http://user:pa123456@localhost:8762/eureka
server:
  port: '9901'
spring:
  application:
    name: gateway-zuul
zuul:
   ignoredServices: "*"
   routes:
    movies:
      path: /movie-info/**
      serviceId: eureka-movie-comps
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#192.168.0.100:eureka-movie-comps:8092 , 192.168.0.100:eureka-movie-comps:8091
      
